name: bob
version: 1.2.0.5

dependencies:
  - base

library:
  exposed-modules: Bob
  source-dirs: src
  dependencies:
    - text

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - bob
      - hspec
