name: AoC2018
version: '0.1.0.0'
category: Lib
author: Zack Kourouma
maintainer: zack@kourouma.me
copyright: 2018 Zack Kourouma
license: BSD3
github: zkourouma/AoC2018

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - text >=1.2.2.0

ghc-options: [-Wall, -Wwarn]

library:
  source-dirs: src
  other-modules:
    - Paths_AoC2018

internal-libraries:
  l-day01: &base-lib
    source-dirs: day01
    other-modules:
      - Paths_AoC2018
    dependencies:
      - AoC2018
      - hspec

data-files:
  - inputs/*

executables:
  day-01: &base-exe
    main: Main.hs
    source-dirs: day01
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -O2]
    other-modules:
      - Paths_AoC2018
    dependencies:
      - AoC2018
  # day-02:
  #   <<: *base-exe
  #   source-dirs: day02

tests:
  day-01-test: &base-test
    source-dirs: day01
    main: Spec.hs
    dependencies:
      - hspec
      - l-day01
