name: aoc2017
version: '0.0.1.0'
synopsis: Advent of Code solutions for 2017 (adventofcode.com/2017)
description: Please see the README on Github at <https://github.com/zkourouma/aoc2017#readme>
category: Web
author: Zack Kourouma
maintainer: zack@kourouma.me
copyright: 2017 Zack Kourouma
license: BSD3
homepage: https://github.com/zkourouma/aoc2017#readme
git: https://github.com/zkourouma/aoc2017

extra-source-files:
- README.md

dependencies:
- base >=4.7 && <5
ghc-options: [-Wall, -Wwarn]

library:
  source-dirs: src
  other-modules:
    - Paths_aoc2017

data-files:
  - input/*

executables:
  day-1:
    main: Main
    source-dirs: day1
    ghc-options: [ -threaded, -rtsopts, -with-rtsopts=-N]
    other-modules:
    - Paths_aoc2017
    dependencies:
    - aoc2017


tests:
  day-1-test:
    main: Spec.hs
